name: drive_safe
description: "Drive safe is a mobile app that promotes safe driving through gamification. Earn points for safe driving, customize your car, and compete in fun games within your network."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  confetti: ^0.8.0 # confettit on the page
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1 # main Riverpod package
  go_router: ^14.6.3 # simplifies navigation and routing
  riverpod_annotation: ^2.6.1 # enables code generation
  flutter_svg: ^2.0.17 # provides the ability to load svg
  json_annotation: ^4.9.0 # enables code generation for json_serializable
  cloud_firestore: ^5.6.3 # enables to use Firebase Cloudstore
  crypto: ^3.0.6 # generates unique string securely
  carousel_slider: ^5.0.0 # carousel widget in leaderboard
  flame: ^1.25.0 # game engine
  flame_riverpod: ^5.4.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flame_tiled: ^2.0.1
  kiosk_mode: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13 # handles code generation. used with riverpod_annotaion, json_serializable packages
  hive_generator: ^2.0.0

  riverpod_generator: ^2.6.3 # enables code generation for providers when used in conjunction with build_runner
  custom_lint: ^0.7.0 # allows defining custom lint rules
  riverpod_lint: ^2.6.3 # provides pre-defined lint rules specifically for Riverpod
  json_serializable: ^6.9.0 # generate JSON serialization code in data model

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

  # Bring in image assets
  assets:
    - assets/images/
    - assets/tiles/
